/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  serverBuildTarget: "vercel",
  server: process.env.NODE_ENV === "development" ? undefined : "./server.js",
  ignoredRouteFiles: ["**/.*"],
  serverDependenciesToBundle: [
    /^rehype.*/,
    /^remark.*/,
    /^unified.*/,
    /^unist.*/,
    /^hast.*/,
    /^bail.*/,
    /^trough.*/,
    /^mdast.*/,
    /^micromark.*/,
    /^decode.*/,
    /^character.*/,
    /^property.*/,
    /^space.*/,
    /^comma.*/,
    /^vfile.*/,
    "mdx-bundler",
    "github-slugger",
    "refractor",
    "emoticon",
    "zwitch",
    "ccount",
    "@agentofuser/remark-oembed",
    "markdown-table",
    "estree-util-is-identifier-name",
    "fault",
    "hastscript",
    "parse-entities",
  ],
  appDirectory: "app",
  serverBuildPath: "api/index.js"
};
