/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  serverModuleFormat: "cjs",
  serverDependenciesToBundle: [
    /^remix-utils.*/,
    /^rehype.*/,
    /^remark.*/,
    /^unified.*/,
    /^unist.*/,
    /^hast.*/,
    /^bail.*/,
    /^trough.*/,
    /^mdast.*/,
    /^micromark.*/,
    /^decode.*/,
    /^character.*/,
    /^property.*/,
    /^space.*/,
    /^comma.*/,
    /^vfile.*/,
    /^mdx.*/,
    /^github-slugger.*/,
    /^redent.*/,
    /^refractor.*/,
    /^emoticon.*/,
    /^zwitch.*/,
    /^ccount.*/,
    /^@agentofuser\/remark-oembed.*/,
    /^markdown-table.*/,
    /^estree-util-is-identifier-name.*/,
    /^fault.*/,
    /^hastscript.*/,
    /^parse-entities.*/,
    /^is.*/,
    /^stringify.*/,
    /^slugify.*/,
    /^@sindresorhus.*/,
    /^@remix-pwa\/.*/,
    "redent",
    "indent-string",
    "@sindresorhus/slugify",
    "@sindresorhus/transliterate",
    "strip-indent",
    "escape-string-regexp",
    "web-namespaces",
    "clsx",
  ],
  appDirectory: "app",
  tailwind: true
};
